
DROP DATABASE IF EXISTS airports_dw;

CREATE DATABASE airports_dw;

USE airports_dw;

CREATE TABLE dim_airport (
    AIRPORT_ID INT,
    AIRPORTNAME VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    PRIMARY KEY (AIRPORT_ID)
);

CREATE TABLE dim_time (
    TIME_ID DATETIME,
    YEAR_ID INT,
    DAY_ID INT,
    MONTH_ID INT,
    MONTH_NAME VARCHAR(255),
    PRIMARY KEY (TIME_ID)
);

CREATE TABLE dim_airline(
    AIRLINE_ID INT,
    AIRLINENAME VARCHAR(255),
    PRIMARY KEY (AIRLINE_ID)
);

CREATE TABLE dim_airplane (
    AIRPLANE_ID INT,
    AIRPLANETYPE INT,
    PRIMARY KEY (AIRPLANE_ID)
);

CREATE TABLE fact_flight (
    FLIGHT_ID INT,
    FLIGHTNUMBER VARCHAR(255),
    AIRPORT_FROM INT,
    AIRPORT_TO INT,
    DATE_FROM DATETIME,
    DATE_TO DATETIME,
    AIRLINE_ID INT,
    AIRPLANE_ID INT,
    PASSENGERS INT,
    REVENUE DOUBLE, 	
    PRIMARY KEY (FLIGHT_ID , FLIGHTNUMBER),
    FOREIGN KEY (AIRPORT_FROM) REFERENCES dim_airport (AIRPORT_ID),
    FOREIGN KEY (AIRPORT_TO) REFERENCES dim_airport (AIRPORT_ID),
    FOREIGN KEY (DATE_FROM) REFERENCES dim_time (TIME_ID),
    FOREIGN KEY (DATE_TO) REFERENCES dim_time (TIME_ID),
    FOREIGN KEY (AIRLINE_ID) REFERENCES dim_airline (AIRLINE_ID), 
    FOREIGN KEY (AIRPLANE_ID) REFERENCES dim_airplane (AIRPLANE_ID)
);
